// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HellwegFinal.Models
{
    public partial class EmployeeAccount
    {
        public int EmployeeIndex { get; set; }
        public string EmployeeUser { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeRole { get; set; }
        public int? EmployeeLogins { get; set; }
    }
}