// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HellwegFinal.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Infractions = new HashSet<Infraction>();
        }

        public int EmployeeIndex { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int? EmproleIndex { get; set; }

        public virtual EmpRole EmproleIndexNavigation { get; set; }
        public virtual ICollection<Infraction> Infractions { get; set; }
    }
}