// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HellwegFinal.Models
{
    public partial class EmpRole
    {
        public EmpRole()
        {
            Employees = new HashSet<Employee>();
        }

        public int EmpRoleIndex { get; set; }
        public string EmpRoleTitle { get; set; }
        public string EmpRoleDescription { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}