// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HellwegFinal.Models
{
    public partial class Infraction
    {
        public int InfractionIndex { get; set; }
        public int? EmployeeIndex { get; set; }
        public int? VehicleIndex { get; set; }
        public int? InfractionTypeIndex { get; set; }
        public DateTime? InfractionDate { get; set; }
        public string Notes { get; set; }

        public virtual Employee EmployeeIndexNavigation { get; set; }
        public virtual InfractionType InfractionTypeIndexNavigation { get; set; }
        public virtual Vehicle VehicleIndexNavigation { get; set; }
    }
}