// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HellwegFinal.Models
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            Infractions = new HashSet<Infraction>();
        }

        public int VehicleIndex { get; set; }
        public int? VehicleOwner { get; set; }
        public string VehiclePlate { get; set; }
        public DateTime? VehicleAge { get; set; }
        public string Color { get; set; }

        public virtual Driver VehicleOwnerNavigation { get; set; }
        public virtual ICollection<Infraction> Infractions { get; set; }
    }
}